In [2]:
import numpy as np
import scipy.linalg as sla

In [3]:
def elimin_gaussiana(a, b, imp=False, norma='inf'):
    # matriz estendida Me
    b = np.mat(b).T
    Me = np.concatenate((a, b), axis=1)
    if imp: print('Matriz estendida: \n', Me, '\n\n')
    if imp: print('=' * 80)
    for j in range(Me.shape[-1] - 2):  # coluna
        if imp: print('Operação na coluna', j)
        if imp: print('=' * 80, '\n\n')
        for i in range(j + 1, Me.shape[0]):  # linha
            Me[i] = Me[i] - (Me[i, j] / Me[j, j]) * Me[j]  # operações com cada linha
            if imp: print('Operação na linha', i, ':', Me[i], '\n')
            if imp: print('Matriz escalonando: \n', Me, '\n')
        if imp: print('=' * 80)
    if imp: print('\nMatriz escalonada: \n', Me, '\n')
    Matriz_A = np.delete(Me, -1, axis=1)  # matriz de coeficientes escalonada
    Vetor_b = Me[:, -1]  # matriz de termos independentes escalonada
    Vetor_x = sla.solve_triangular(Matriz_A, Vetor_b)  # solução do sistema escalonado
    if imp: print('=' * 80, '\n\nSolução do sistema: \n', Vetor_x)
    # verificação do erro do sistema
    if norma is 'inf': norma = np.inf
    if norma is '-inf': norma = -np.inf
    Erro = sla.norm(b - a.dot(Vetor_x), ord=norma)
    return (Matriz_A, Vetor_b, Vetor_x, Erro)


In [4]:
a = np.array([[2,3,-1],[4,4,-3],[2,-3,1]])
b = np.array([5,3,-1])
M = elimin_gaussiana(a,b)
M

(matrix([[ 2,  3, -1],
         [ 0, -2, -1],
         [ 0,  0,  5]]), matrix([[ 5],
         [-7],
         [15]]), array([[1.],
        [2.],
        [3.]]), 0.0)

In [10]:
a = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]]).astype(float)
b = np.array([1, 2, 0]).astype(float)

#Tive que adicionar o tipo pra minha função funcionar



In [7]:
elimin_gaussiana(a, b)

/home/marlon/venv/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in long_scalars
  # This is added back by InteractiveShellApp.init_path()
/home/marlon/venv/lib/python3.7/site-packages/ipykernel_launcher.py:11: RuntimeWarning: invalid value encountered in multiply
  # This is added back by InteractiveShellApp.init_path()


LinAlgError: singular matrix: resolution failed at diagonal 1

O erro ocorre pois depois da primeira subtração, a segunda linha passa a ter os valores [0, 0, -2, -2], assim, no momento em que houver a subtração da segunda terceira linha, teremos zero como pivô.

In [7]:
def elim_gaussiana(A, b, pivotamento=None, imp=False, norma='inf'):
    b = np.mat(b).T
    me = np.array(np.concatenate((A, b), axis=1))
    n = len(me)

    if imp:
        print('Matriz estendida:\n{}\n'.format(me))
    if imp:
        print('=' * 80)

    # Eliminação
    for k in range(n - 1):
        if pivotamento:
            # Pivô
            maxindex = abs(me[k:, k]).argmax() + k
            if me[maxindex, k] == 0:
                raise ValueError("Matriz é singular.")
            # Trocas
            if maxindex != k:
                me[[k, maxindex]] = me[[maxindex, k]]

                if imp:
                    print("Troca entre as linhas {} e {}".format(k, maxindex))
                if imp:
                    print('Matriz escalonando:\n{}\n'.format(me))
        else:
            if me[k, k] == 0:
                raise ValueError("Pivô é zero. Tente com a variável \'pivoteamento\' como True.")

        for linha in range(k + 1, n):
            mult = me[linha, k] / me[k, k]
            me[linha, k:] = me[linha, k:] - mult * me[k, k:]
            if imp:
                print('Operação na linha {}: {}'.format(linha, me[linha]))
            if imp:
                print('Matriz escalonando: \n {} \n'.format(me))

    # Retrosubstituição

    if imp:
        print('Matriz escalonada:\n{}\n'.format(me))

    matriz_a = me[:, :-1]  # matriz de coeficientes escalonada
    vetor_b = me[:, -1]  # matriz de termos independentes escalonada
    vetor_x = sla.solve_triangular(matriz_a, vetor_b)  # solução do sistema escalonado

    if imp:
        print('=' * 80, '\n\nSolução do sistema: \n', vetor_x)

    # Verificação do erro do sistema
    if norma is 'inf':
        norma = np.inf
    if norma is '-inf':
        norma = -np.inf
    erro = sla.norm(b - A.dot(vetor_x), ord=norma)

    return matriz_a, vetor_b, vetor_x, erro


In [11]:
elim_gaussiana(a, b, pivotamento=True)


(array([[ 4. ,  4. ,  2. ],
        [ 0. , -1. , -2. ],
        [ 0. ,  0. ,  0.5]]),
 array([ 2. , -1. ,  0.5]),
 array([ 1., -1.,  1.]),
 3.0)

Questão 2

In [18]:
x = np.array([1., 1., 1.])
x1 = np.array([4.5, 0, 1.01])

erro_a = x - x1
erro_r = erro_a/x1
print("Erro absoluto: {}\nErro releativo: {}".format(erro_a, erro_r))

Erro absoluto: [-3.5   1.   -0.01]
Erro releativo: [-0.77777778         inf -0.00990099]


Questão 3

In [12]:
a = np.array([[1., 4, 52], [27, 110, -3], [22, 2, 14]])
b = np.array([57., 134, 38])

In [13]:
elim_gaussiana(a, b, pivotamento=True)


(array([[ 27.        , 110.        ,  -3.        ],
        [  0.        , -87.62962963,  16.44444444],
        [  0.        ,   0.        ,  52.09721048]]),
 array([134.        , -71.18518519,  52.09721048]),
 array([1., 1., 1.]),
 173.0)

Como podemos ver, o resultado com pivoteamento parcial é o correto, ou seja, não houve erro.

Questão 4 - Já implementada na questão 1

Questão 5