In [16]:
import numpy as np
import scipy.linalg as sla

###Questão 2

In [2]:
#Arrays de teste
Au = np.array([[3, 4, -5, 1], [0, 1, 1, -2], [0, 0, 4, -5], [0, 0, 0, 2]])
bu = np.array([-10, -1, 3, 2])

In [3]:
def retro_sub(b, A):
    n = len(b)
    x = np.zeros_like(b)
    x[n-1] = b[n-1] / A[n-1][n-1]
    
    for i in range(n-2, -1, -1):
        soma = b[i]
        for j in range(i+1, n, 1):
            soma = soma - A[i][j]*x[j]
            x[i] = soma / A[i][i]
    return x



In [11]:
out_u = retro_sub(bu, Au)
out_u

array([ 1, -1,  2,  1])

###Questão 3

In [12]:
def prog_sub(b, A):
    n = len(b)
    x = np.zeros_like(b)
    x[0] = b[0] / A[0][0]

    for i in range(1, n):
        soma = b[i]
        for j in range(0, i):
            soma = soma - A[i][j] * x[j]
            x[i] = soma / A[i][i]
    return x

In [13]:
Al = np.array([[2, 0, 0, 0], [-5, 4, 0, 0], [-2, 1, 1, 0], [1, -5, 4, 3]])
bl = np.array([2, 3, -1, -10])

In [14]:
out_l = prog_sub(bl, Al)
out_l

array([ 1,  2, -1,  1])

###Questão 4

In [18]:
out_npu = sla.solve_triangular(Au, bu)
out_npu

array([ 1., -1.,  2.,  1.])

In [20]:
out_npl = sla.solve_triangular(Al, bl, lower=True)
out_npl

array([ 1.,  2., -1.,  1.])

Os métodos implementados apresentam resultados iguais aos do método solve_triangular.